SSAFYnity/Job-Preparation-Challenge-4th

Baekjoon/쿠키의신체측정/쿠키의신체측정_박철순.java
#1 
쉬운 문제였습니다. 
- 머리, 심장 위치가 핵심 
X
=> solved 쿠키의신체측정 - 252ms 23500kb

Baekjoon/쿠키의신체측정/쿠키의신체측정_강정훈.java
#1 
난이도가 쉬웠습니다.
신체가 비틀리거나 하는 것 없이 무조건 위에서 아래 방향으로 입력이 들어온다는 점을 이용해서 머리를 탐색 후 심장 위치를 찾고 각 부위별 탐색을 하면 쉽게 답을 알 수 있습니다.
=> solved 쿠키의 신체 측정 - 240ms 19380KB

Baekjoon/쿠키의신체측정/쿠키의신체측정_김인호.java
https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/1
20125
머리 기준으로 심장 찾고 나머지 팔다리 찾은 구현이었습니다.
머리 기준으로 심장 찾고 나머지 팔다리 찾았습니다.
감사합니다.
- [ o ] Convention(commit, pr 제목)이 올바른가요?
- [ o ] 괄호 내 안내문은 삭제하셨나요?
- [ o ] 본인의 체감 난도 Label을 등록했나요?
- [ o ] 제출자 확인 사항을 모두 확인하셨나요?
=> solved 쿠키의 신체측정 - 164ms 20876kb

Programmers/캐시/일차캐시_김인호.java
[1차캐시](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/15)
LRU 기법을 복습하면서 풀 수 있었습니다. 
Deque를 사용해서 가장 오래 사용하지 않은 것들을 제거하는 방향으로 구현했습니다. 
=> solved 1차캐시 - 40.70ms 108mb

Baekjoon/정육점/정육점_김인호.java
[정육점](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/29)
반례가 많아서 좀 어려웠습니다.
가격을 우선으로 정렬 후 같은 경우 무게는 내림차순으로 정렬했습니다.
또한 같은 가격일 경우 누적합을 계산하였습니다
=> solved 정육점 416ms 42732mb

Programmers/캐시/캐시_강정훈.java
#15 
무난한 문제였습니다
다양한 풀이 방식이 있겠지만, 저는 캐시 데이터를 LinkedHashSet 구현체를 이용하여 순서와 캐싱이 보장되게 풀이하였습니다.
=> solved 캐시 - 51.57ms 139MB

Baekjoon/정육점/정육점_강정훈.java
#29 
단순히 생각했다가 엣지케이스가 꽤 있어서 조금 애먹었던 문제였습니다.
정렬 순서와 엣지 케이스를 잘 구상하는 것이 중요한 것 같습니다.
=> solved 정육점 - 536ms 44936KB

Programmers/등대/등대_최지수.java
=> solved 등대 - 59.14ms 130MB

Programmers/캐시/캐시_최지수.java
#15 
괜찮았습니다.
LinkedHashMap을 사용했습니다.
=> solved 캐시 - 36.04ms 105MB

Baekjoon/정육점/정육점_최지수.java
=> solved 정육점 - 376ms 41496KB

Baekjoon/빙산/빙산_최지수.java
=> solved 빙산 - 568ms 108292KB

Programmers/산모양타일링/산모양타일링_최지수.java
=> solved 산모양타일링 - 8.19ms 80.1MB

Programmers/등산코스정하기/등산코스정하기_최지수.java
=> solved 등산코스정하기 - 2258.06ms 440MB

Baekjoon/쿠키의신체측정/쿠키의신체측정_김수빈.java
=>  solved 쿠키의 신체측정 - 228mb 23.152mb

Programmers/캐시/캐시_김수빈.java
#15 캐시
어려웠다. 처음에 우선순위큐인줄 알고 잘못접근했다가 시간 낭비를 꽤나 했다.
- 이중연결리스트
- 해쉬맵
=> unsolved 캐시

Programmers/산모양타일링/산모양타일링_김수빈.java
=> unsolved 산 모양 타일링 - 6.81ms, 93.2mb

Baekjoon/정육점/정육점_박영빈.java
#29 
처음엔 DP라고 생각해서 한참 헤맸습니다.. 그리드랑 DP랑 구분하기 어려워요.
- 정렬
- 그리드
- 배열 정렬에 관한 문제여서 사용자 정의 클래스에서 Comparable 인터페이스를 사용하거나, Comparator 인터페이스, 익명 클래스, 람다식 등의 방법 중 하나를 택했습니다.
혹시 DP로 푸는 방법도 있나요? DP랑 그리드랑 구분하는 방법이 있을까요
=> solved 정육점 - 480ms 44548KB

Baekjoon/빙하/빙하_박영빈.java, Baekjoon/정육점/정육점_박영빈.java
#42 
BFS와 DFS가 적절히 섞인 문제 같은데, 모든 반례들을 채 못 찾아내서 끝내 풀지 못했습니다. 
스파게티 코드가 된 것 같아요.
- BFS, DFS
- 계속 다른 코드를 참고하며 코드를 간결하게 수정하려고 하겠지만, 정확히 어떤 부분을 개선해야 할 지 잘 모르겠습니다..
- 
=> solved 빙하 - 660ms 299084KB

Baekjoon/쿠키의신체측정/쿠키의신체측정_조은영.cpp
#1 
단순 구현이라 평이했습니다.
- 머리, 심장, 왼팔 길이, 오른팔 길이, 허리 길이, 왼다리, 오른다리 순서로 찾았습니다.
=> solved 쿠키의신체측정 - 12ms 2.8mb

Programmers/산모양타일링/산모양타일링_조은영.cpp
#55 
어려웠습니다. dp라는건 알겠는데 규칙찾기가 어려웠네요..
- 풀이가 굉장히 다양한데 저는 tops가 있는 경우와 없는 경우로 나누어 수식 도출하는 방법이 제일 이해가 잘됐습니다.
=> solved 산모양타일링 - 1.23ms 6.81mb

Programmers/1차캐시/1차캐시_박단비.py
#15 
보통이었습니다.
- LRU에 대한 이해를 바탕으로 한 구현
=> solved 1차캐시 - 72.63ms 17.6mb

Baekjoon/정육점/정육점_박단비.py
#29 
보통이었습니다.
- 정렬
- 같은 무게일 경우 다 더해야 함
=> solved 정육점 - 2820ms 57288kb

Baekjoon/빙산/빙산_박단비.py
#42 
쉬웠습니다.
- BFS
- 빙하를 녹이기 위해서는 BFS를 돌면서 따로 배열에 저장해줘야 함.
=> solved 빙산 - 3132ms 35028kb

Programmers/캐시_김지환.js
#21 
쉬웠다. 큐로 풀면 되는데, shift가 기억이 안나서 다소 복잡하게 풀었던 것 같다.
- 큐
=> solve 캐시 - 59.76ms 42.5mb

Programmers/기지국설치/기지국설치_김지환.js
#110 
어려웠다. 배열로 풀다가, N이 2억인걸 늦게 봐서 다시 풀었다.
- 구현
=> solved 기지국설치 - 2.02ms 36.9MB

Baekjoon/정육점/정육점_김지환.js
#29 
많이 헤맸다. 중첩 반복문으로 시간 초과가 나와서, 다른 방법을 찾느냐 고생했다.
- 정렬, 분기
=> solved 정육점 - 376ms 44984kb

Programmers/표편집/표편집_김지환.js
#85 
어려웠다. 반복문으로 풀려고 했는데, 시간 초과가 나와서 연결리스트를 활용하여 해결하였다.
- 연결리스트
=> solved 표편집 - 272ms 160mb

Programmers/캐시/캐시_옥수빈.java
=> solved 캐시 - 35.68ms 122mb

Baekjoon/쿠키의신체측정/정육점/정육점_옥수빈.java
=> solved 정육점 - 548ms 61.020mb

Baekjoon/빙산/빙산_옥수빈.java
=> solved 빙산 - 660ms 75.888mb

Baekjoon/테트로미노/테트로미노_김범규.java
#73 
초기에 19방식을 모조리 메서드로 만들어서 풀다가 코드가 250줄이 넘어가서... 다시 delta를 사용하여 풀었습니다. 구현에는 아직 약한 것 같습니다.
테트로미노로 나올 수 있는 도형의 초기 점을 잡고, 이후 나갈 수 있는 방향을 3차원 배열에 담았습니다. (T자형은 가운데를 기점으로, 나머지는 왼쪽 상단 혹은 하단 으로 잡았습니다.)
시간을 더 줄일 수 있는 방법이 있을까요...?
=> solved 테트로미노 484ms 31824mb

Baekjoon/미세먼지안녕/미세먼지안녕_박은정.java
#123 
- 회전이 어려웠다 
- 회전을 추가적인 배열을 사용하지 않고 하는 방안 
=> sovled 미세먼지안녕 - 236ms 26008kb

Baekjoon/빙산/빙산_강정훈.java
#42 
예외 케이스를 생각 못한 부분이 있어서 디버깅에 시간이 좀 걸렸습니다.
모든 빙산 좌표에서 동시에 녹아야하는데 해당 부분을 놓쳐서 시간이 걸렸습니다.
동시에 빙산을 녹아야하는 부분을 생각한다면 쉽게 아이디어가 떠오를 것 같습니다.
남아있는 빙산의 크기와 임의의 한 빙산에서 순회를 했을때 끊기지 않고 크기가 같다면 분리되지 않음을 파악하면 되는 것 같습니다.
=> solved 빙산 - 536ms 80576KB

Baekjoon/테트로미노/테트로미노_강정훈.java
#73 
접근방식을 고민을 많이 했던 문제였습니다. 그래프 탐색으로 풀기에는 안되는 모양이 있어서 고민이 많았습니다.
입력 범위를 통해 완전탐색으로 풀 수 있는 가능성을 체크하고, 안 되는 도형에 대해 예외처리를 어떻게 해야할지 고민하면 되는 문제 인 것 같습니다.
=> solved 테트로미노 - 736ms 32452KB

Programmers/표편집/표편집_강정훈.java
#84 
이 전에 풀어봤던 문제라 LinkedList를 직접 구현하는 형태의 문제라는 것을 파악하기 쉬웠습니다.
해당 문제가 LinkedList를 간접적으로 구현할 수 있어야 되는 문제라는 것을 깨달으면 절반 이상 정답이라고 생각됩니다.
LinkedLIst 내부에 private static Class로 Node라는 클래스가 있고 내부에 prev, next라는 필드가 있어 이를 바탕으로 연결 리스트를 구현하는 방식을 알고 있다면, 풀 수 있습니다.
=> solved 표 편집 - 280.43ms 145MB

Programmers/표 편집/표편집_김범규.java
#84 
Double Linked List를 알면 쉬웠을 것 같은데... 아직 시간 복잡도랑 자료구조가 익숙하지 않아서 많이 어려웠습니다.
초기에는 ArrayList로 풀어나갔으나, 삭제, 복구에서 시간 초과가 발생하였고 검색을 통해 Double Linked List를 공부하고 다시 풀었습니다.
removed 배열을 통해 삭제된 곳을 체크하여 혹시나 삭제된 인덱스에 k가 가지 않도록 방지하였습니다.
1. 지금 처럼 prev, next를 각 배열로 선언한 방식이 아니라, Node 구조체로 선언해서 푸는 방식은 Node 구조체에서 prev, next 말고도 value를 추가로 선언하기 때문에 메모리가 더 발생하는건가요?
=> solved 표편집 114.02ms 107mb

Baekjoon/리모컨/리모컨_김범규.java
#94 
표 편집보다는 풀기 쉬웠던 것 같습니다.
set을 활용해서 검색 시간을 O(1)로 줄였습니다.
또 M이 0인경우와 N 이 100경우 각각 예외처리를 하면서, 출력에 이상이 없도록 하였습니다!
=> solved 리모컨 236ms 47088kb

Programmers/기지국설치/기지국설치_김범규.java
#107 
앞 선 두 문제보단 쉬웠던 것 같습니다.
배열 생성 없이 station만 이용하여 해결하였습니다.
=> solved 기지국설치 0.22ms 94mb

Baekjoon/테트로미노/테트로미노_김수빈.java
#73 테트로미노
쉬운듯 어려운듯 너무 주먹구구식으로 풀어서 틀린 것 같다 다시 풀어볼 예정이다.
- 브루트포스
=> unsolved 테트로미노 - 2000ms 518mb

Baekjoon/리모컨/리모컨_김수빈.java
#94 리모컨
시간 촉박한 상태에서 풀어서 자꾸 틀렸다.... 정각이 지나고 더풀어볼 예정이다.
- 브루트포스
=> solved 리모컨 - 292ms 64868kb

Programmers/기지국설치/기지국설치_김수빈.java
#107 기지국 설치
접근은 맞았으나 너무 많이 탐색으로 초반 시간초과 오류 발생
=> solved 기지국 설치 - 1.14ms 72.7mb

Baekjoon/미세먼지안녕/미세먼지안녕_김수빈.java
#123 미세먼지 안녕!
매일 한시간 남겨두고 풀려고 하니 못푼다.. 오전에 풀어보려고 노력해야겠다.
새벽에 더 풀어볼 예정
- 브루트포스 단순무식
=> solved 미세먼지 안녕 - 352ms 128344kb

Programmers/표편집/표편집_김인호.java
[표편집](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/84)
생각할 게 많아 오래걸렸습니다
연결리스트방식으로 했습니다.
=> Solved 표편집 - 0ms 0kb

Baekjoon/테트로미노/테트로미노_김인호.java
[테트로미노](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/73)
DFS활용했습니다~!
방향이 중요했습니다.
=> solved 테트로미노- 792ms 35844kb

Baekjoon/리모컨/리모컨_김인호.java
[리모컨](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/94)
그리디한 구현으로 했다가 마지막 반례에 막혀서 힌트보고 브루트포스로 풀었습니다.
다 되는 값들로만 찾고 최솟값을 갱신하는 방식입니다.
결국은 한번에 안끝내고 끝까지 돕니다.
=> solved 리모컨_김인호 - 252ms 99000kb

Programmers/기지국설치/기지국설치_김인호.java
[기지국설치](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/107)
갭 차이를 이용했습니다.
한배열접근보단 갭으로 접근해서 단축시켰습니다.
=> solved 기지국설치 - 0.87ms 55.5mb

Baekjoon/미세먼지안녕/미세먼지안녕_김인호.java
[미세먼지안녕](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/123)
오래걸렸습니다 2시간..정도
큐를 활용했습니다.
=> solved 미세먼지안녕 - 252ms 33428kb

Baekjoon/테트로미노/테트로미노_박은정.java
=> solved 테트로미노 - 604ms 36476kb

Baekjoon/표편집/표편집_박은정.java
#84 
- 어려웠다. 
- 처음에 시간초과가 발생했다.
- 처음 코드는 삭제되지 않은 다음 인덱스를 찾기 위해 모든 행을 순차 탐색하였고 많은 행이 삭제된 경우 비효율적이었다.
- Java TreeSet 사용하여 삭제되지 않은 행을 관리하였다.
- LinkedList를 직접 구현하는 방식도 해봐야겠다. 
=> solved 표편집 - 0ms 0mb

Baekjoon/리모컨/리모컨_박은정.java
#94 
- 중간..?
- 이동하려고 하는 채널과 가장 가까운 채널을 브루트포스로 찾는다. 
=> solved 리모컨 - 336ms 98152kb

Baekjoon/리모컨/리모컨_옥수빈.java
=> solved 리모컨 - 456ms 217mb

Baekjoon/드래곤커브/드래곤커브_박은정.java
#142 
- 규칙 찾는게 어려웠다 
- 방향에 대한 규칙 찾기 
- 해당 방향으로 움직이며 표시하기
=> solved 드래곤커브 - 112ms 1440kb

Programmers/보석쇼핑/보석쇼핑_박은정.java
#174 
어려웠다
- 구현 중심(슬라이딩윈도우(?))
- 이런 류의 문제가 어렵네요 ㅠ
=> solved 보석쇼핑 - 0ms 0kb

Baekjoon/트리의지름/박은정_트리의지름.java
#168 
중간 
- 구현은 어렵지 않았지만 트리의 속성을 알아야 하는 문제 
=> solved 트리의지름 - 832ms 97144kb

Baekjoon/빙산/빙산_김부경.py
=> solved 빙산 - 728ms 137916KB

Programmers/등산코스정하기/등산코스정하기_김부경.py
=> solved 등산코스정하기 - 522.41ms 88.9mb

Baekjoon/테트로미노/테트로미노_김부경.py
=> solved 테트로미노 - 1036ms 117488kb

Baekjoon/리모컨/리모컨_김부경.py
=> solved 리모컨 - 244ms 110760kb

Programmers/기지국설치/기지국설치_김부경.py
=> solved 기지국설치 - 2.59ms 10.2mb

Baekjoon/미세먼지안녕/미세먼지안녕_김부경.py
=> solved 미세먼지안녕 - 316ms 112564kb

Programmers/불량사용자/불량사용자_김부경.py
=> solved 불량사용자 - 73.24ms 10.1mb

Baekjoon/드래곤커브/드래곤커브_김부경.py, Programmers/경주로건설/경주로건설_김부경.py
=> solved 드래곤커브 - 36ms 32412kb

Baekjoon/미세먼지_안녕/미세먼지_안녕_김범규.java
#123 
공기 청정기 회전이 제일 헷갈렸습니다..
공기청정기를 회전할 때 순차적으로 하는 것이 아닌 역으로 값을 옮겨 temp 저장 없이 풀었습니다.
=> solved 미세먼지안녕 332ms 33244kb

Programmers/불량사용자/불량사용자_김범규.java
#133 
dfs를 이용한 문제였습니다. 코드 자체는 어렵지 않았던 것 같습니다.
HashSet을 이용해 조합을 저장하면서, 중복된 조합은 저장되지 않게 함으로써 경우의 수를 추가하였고, 마지막 set의 길이를 출력하였습니다.
=> solved 불량사용자 91.67ms 125mb

Baekjoon/드래곤커브/드래곤커브_김범규.java
#142 
방향 감각 잡는게 어려웠습니다.. 나머지는 괜찮았습니다.
point 구조에서 @Override 관련 작성은 문서를 참고했습니다.
배열을 이용하면 무조건 100 * 100 반복하게 될 것 같아서 Set을 이용해서 좌표를 저장하고, 이 set안에 정사각형을 만드는 좌표가 있는지 검사했습니다.
=> solved 드래곤커브 128ms 15668kb

Programmers/경주로건설/경주로건설_김범규.java
#153 
dfs로 풀어보다가 시간초과 나와서 bfs로 옮겼습니다.
3차원 boolean 배열을 이용해 방향 접근에 대해서도 처리 해줬고,
board배열안에 작은 값이 이미 있으면 접근 안하도록 예외처리했습니다.
=> sovled 경주로건설 8.81ms 82.5mb

Programmers/보석쇼핑/보석쇼핑_김범규.js
#174 
인덱스 비교만 잘 생각하면 평이한 문제였던 것 같습니다.
Set을 통한 중복제거
=> solved 보석쇼핑 6.31ms 38mb

Programmers/기지국설치/기지국설치_강정훈.java
#107 
프로그래머스 Lv3치고는 쉬웠습니다. Lv2로 내려가도 될 것 같은 문제였습니다.
N의 범위를 보면 N의 범위에서 일일이 탐색하는 것은 불안하다는 것을 알 수 있습니다.
기지국을 새로 설치하는 판단 여부를 어떻게 효율적으로 처리할 수 있을 지를 중점적으로 풀면 됩니다.
=> solved 기지국 설치 - 1.40ms 87.5MB

Baekjoon/리모컨/리모컨_강정훈.java
#94 
완전 탐색이 아닌 방식을 찾으려다가 시간을 너무 많이 사용하였습니다. 
완전 탐색임을 알아채는 것이 중요한 것 같습니다. 완전 탐색으로도 풀린다는 것을 알면 구현 난이도 자체는 어렵지 않습니다. 
=> solved 리모컨 - 260ms 82708KB

Programmers/경주로건설/경주로건설_강정훈.java
#153 
방향이 추가된 BFS문제인데, 비슷한 유형이 DP로도 나오는 경우가 있어서 고민을 조금 했었습니다.
방향이 더해진 BFS
=> solved 경주로 건설 - 10.28ms, 93.8MB

Programmers/불량사용자/불량사용자_김인호.java
[불량사용자](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/133)
Set을 활용해서 쉽게 해결했습니다. 
-  Set 활용 
=> Solved 불량사용자 - 85ms 123mb

Baekjoon/드래곤커브/드래곤커브_김인호.java
[드래곤커브](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/142)
어려웠어요
초기 방향을 저장하고, 세대를 증가시키면서 새로운 방향을 추가
=> solved 드래곤커브 112ms 13200kb

Baekjoon/트리의지름/트리의지름_김인호.java
[트리의지름](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/168)
노드 클래스와 BFS 활용했습니다.
BFS 사용했습니다.
=> solved 트리의지름 1512ms 311988kb

Programmers/보석쇼핑/보석쇼핑_김인호.java
[보석쇼핑](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/174)
그리디 같았는데,, 아니었네요
그리디로 접근했었는데, 반례가 있어서 투 포인터로 접근했습니다. 
=> Solved 보석쇼핑 70.04ms 81.5mb

Baekjoon/주사위굴리기/주사위굴리기_김인호.java
[주사위굴리기](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/190)
어려웠던 구현입니다
생성자 활용했습니다.  
=> Solved 주사위굴리기 192ms 14932kb

Programmers/보석쇼핑/보석쇼핑_박단비.py
=> solved 보석쇼핑 - 83.60ms 17.mb

Programmers/등산코스정하기/등산코스정하기_박단비.py
#63 
어려웠습니다. 다익스트라에 대해 더 공부해야겠다고 느꼈습니다.
- 다익스트라
=> unsolved 등산코스정하기 - 534ms 87.8mb

Baekjoon/리모컨/리모컨_박단비.py
=> solved 리모컨 - 1044ms 32412kb

Programmers/기지국설치/기지국설치_박단비.py
=> solved 기지국설치 - 4.36ms 10.9mb

Programmers/불량사용자/불량사용자_박단비.py
=> solved 불량사용자 - 295.25ms 10.4mb

Programmers/경주로건설/경주로건설_박단비.py
=> solved 경주로건설 - 133.34ms 10.4mb

Baekjoon/주사위굴리기/김범규_주사위굴리기.java
#190 
동쪽 서쪽 빼곤 다 용이했습니다.
1. 동쪽, 서쪽 이동시 바닥도 변경된다는 점
2. 값 이동은 좌표 이내에서만 수행해야할 것
3. 제출자의 풀이코드의 좋은 점 혹은 개선사항을 남기고 Approve 해주세요.
=> solved 주사위굴리기 136ms 14860kb

Programmers/단속카메라/단속카메라_김범규.java
#194 
정렬만 할줄알면 쉬운 문제인것같습니다.
출차 위치 오름차순 정렬 정렬
=> solved 단속카메라 15.52ms 58.3mb

Baekjoon/내리막길/내리막길_김범규.java
#207 
dp를 잘생각해야하는 문제
dp + dfs 결합
=> solved 내리막길 352ms 35532kb

Programmers/경주로건설/옥수빈_경주로건설.java
=> solved 경주로 건설 - 6.85ms 91.1mb

Programmers/보석쇼핑/보석쇼핑_옥수빈.java
=> solved 보석 쇼핑 - 108.25ms 91.9mb

Programmers/단속카메라/단속카메라_옥수빈.java
=> solved 단속카메라 - 10.48ms, 83.9mb

Baekjoon/테트로미노/테트로미노_최지수.java
=> solved 테트로미노 - 3412ms 311208KB

Programmers/표편집/표편집_최지수.java
#84 
어려웠습니다.
객체지향과 링크드리스트를 잘 활용해야 했습니다.
=> solved 표편집 - 326.35ms 143MB

Baekjoon/리모컨/리모컨_최지수.java
=> solved 리모컨 - 68ms 11576KB

Programmers/기지국설치/기지국설치_최지수.java
=> solved 기지국설치 - 1.19ms 54.8MB

Baekjoon/미세먼지안녕/미세먼지안녕_최지수.java
#123 
괜찮았습니다.
단순 구현이었습니다. 
시계 방향, 반시계 방향 순환을 이렇게 다 코딩하는 거 말고 (d+3) % 4 이런 느낌으로 자동화하고 싶은데 이 문제에서 성공하신 분 계실까요?
=> solved 미세먼지안녕 - 244ms 17664KB

Programmers/불량사용자/불량사용자_최지수.java
#133 
괜찮았습니다.
백트래킹 사용했습니다.
중복 선택지를 가지는 밴 아이디 체크할 때 비트 마스킹을 사용하니 메모리가 조금 더 절약된 거 같습니다.
=> solved 불량사용자 - 17.91ms 88.7MB

Baekjoon/드래곤커브/드래곤커브_최지수.java
#142 
괜찮았습니다.
규칙만 찾으면 단순 구현으로 풀리는 문제였습니다.
=> solved 드래곤커브 - 76ms 11904KB

Programmers/경주로건설/경주로건설_최지수.java
#153 
까다로웠습니다.
가로로 도착했는지 세로로 도착했는지 나눠 다익스트라 사용했습니다.
=> solved 경주로건설 - 2.87ms 77.4MB

Baekjoon/트리의지름/트리의지름_최지수.java
#168 
메모리 관리가 생각보다 어려웠습니다.
트리의 특성(어쨌든 모든 노드가 다 이어져있긴 하다)을 이해하고 풀면 좋고, dfs 썼습니다.
=> solved 트리의지름 - 584ms 92300KB

Programmers/보석쇼핑/보석쇼핑_최지수.java
=> solved 보석쇼핑 - 64.93ms 81.3MB

Baekjoon/트리의지름/강정훈_트리의지름.java
#168 
트리의 지름 규칙을 다시 복습하는 좋은 문제였습니다.
트리의 특징과 트리의 지름이라는 문제의 증명을 이해하고 외워두면 쉽게 풀 수 있는 문제입니다. 
=> solved 트리의 지름 - 736ms, 102344KB

Programmers/보석쇼핑/보석쇼핑_강정훈.java
#174 
gems의 input 크기, 그리고 구하는 것이 특정 구간을 구하는 것을 보고 이진 탐색, 투 포인터를 떠올렸는데 투 포인터가 적합해보여 투포인터로 풀 수 있었습니다.
투 포인터인 것은 금방 알았지만, 문제에서 제시한 부분을 투 포인터로 구현하는데 있어서 고민을 많이 했습니다.
가령, 문제에서 start를 오른쪽으로 옮기기 위해서는 투포인터처럼 특정 조건이 필요했지만, end의 경우는 전체 보석을 체크해야했기 때문에 이를 구분하는 아이디어에 대한 고민을 많이 했습니다.
문제에서 구간을 요구하는 점과 gems의 input 크기를 고려하여 투포인터를 떠올릴 수 있어야 풀 수 있는 문제 
투포인터를 떠올리더라도 일반적으로 start와 end가 특정 조건에따라 index를 옮기는 반면 해당 문제는 end를 전부 순회하는 방식으로 구현해야하는 점을 떠올려야합니다.
=> solved 보석 쇼핑 - 77.09ms, 82.1MB

Programmers/단속카메라/강정훈_단속카메라.java
#194 
정석적인 최소힙 또는 도착지점 정렬로 구간 만족하는 값 구하기 
비슷한 유형의 풀이를 많이 풀어보면 이해가 잘 됨
=> solved 단속카메라 - 9.10ms 59MB

Programmers/단속카메라/단속카메라_최지수.java
=> solved 단속카메라 - 7.75ms 55.6MB

Baekjoon/내리막길/내리막길_최지수.java
=> solved 내리막길 - 284ms 39592KB

Baekjoon/오큰수/오큰수_박은정.java
=> solved 오큰수 888mss 156536kb

Baekjoon/내리막길/내리막길_박은정.java
=> solved 내리막길 - 356ms 37224KB

Baekjoon/오큰수/오큰수_김범규.java
=> solved 오큰수 880ms 148016kb

Programmers/풍선터트리기/풍선터트리기_김범규.java
#231 
생각이 어려운 문제
처음과 마지막 풍선은 반드시 살아남는다?
=> solved 풍선_터트리기  14.31ms 129mb

Programmers/보행자천국/보행자천국_김범규.java
#247 
어려워서 관련 정보 블로그를 활용했습니다.
전체 탐색을 하면서, 아래에서, 좌측에서 올때를 구분하여 각각 값을 저장해줬습니다.
=> solved 보행자천국 99.05ms 117mb

Baekjoon/이분그래프/이분그래프_김범규.java
#239
bfs를 활용
같은레벨 다른색이면 이분그래프 아님
=> solved 이분그래프 864ms 272404mb

Baekjoon/내리막길/내리막길_김인호.java
[내리막길](https://github.com/SSAFYnity/Job-Preparation-Challenge-4th/issues/207)
맵 사이즈가 넓어서 dp 사용했습니다.
이미 방문한 곳은 재 방문하지 않음
=> Solved 내리막길 276ms 38812kb
